# Generated by Django 5.1.3 on 2024-12-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbolsa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
