# Generated by Django 5.1.3 on 2024-12-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbolsa', '0002_accion_cantidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accion',
            name='cantidad_disponible',
        ),
    ]
